name: Scrape Yandex Reviews

on:
  schedule:
    - cron: '0 3 * * *'  # Каждый день в 03:00 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      - name: Run scraper
        run: python glaze-reviews.py

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add reviews.json || echo "No changes to commit"
          git commit -m "Auto update reviews" || echo "Nothing to commit"
          git push
